<?php

namespace App\Livewire\WorkOrders;

use App\Actions\Maintenance\TransitionWorkOrderStatus;
use App\Enums\WorkOrderStatus;
use App\Livewire\Concerns\InteractsWithCurrentUser;
use App\Models\Vendor;
use App\Models\WorkOrder;
use Flux\Flux;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Collection;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Title;
use Livewire\Component;
use LogicException;

/**
 * A vendor's own list of assigned jobs, across every community they work in for this company.
 * Covers both requests raised by a resident and ones generated by a preventive-maintenance
 * schedule, since a vendor's access is scoped to their assignments, not to a community.
 */
#[Title('My work orders')]
class MyWorkOrders extends Component
{
    use InteractsWithCurrentUser;

    /** @var array<int, string> */
    public array $completionNotes = [];

    public function mount(): void
    {
        abort_if($this->vendor() === null, 403);
    }

    /**
     * @return Collection<int, WorkOrder>
     */
    #[Computed]
    public function workOrders(): Collection
    {
        return WorkOrder::query()
            ->where('assigned_vendor_id', $this->vendor()?->id)
            ->whereNotIn('status', [WorkOrderStatus::Completed, WorkOrderStatus::Cancelled])
            ->with(['community', 'serviceRequest.unit.building'])
            ->orderBy('due_on')
            ->latest('id')
            ->get();
    }

    public function transitionTo(int $workOrderId, string $status, TransitionWorkOrderStatus $transitionWorkOrderStatus): void
    {
        $workOrder = $this->findWorkOrder($workOrderId);

        $this->authorize('updateProgress', $workOrder);

        try {
            $transitionWorkOrderStatus->handle(
                $workOrder,
                WorkOrderStatus::from($status),
                $this->completionNotes[$workOrderId] ?? null,
            );
        } catch (LogicException $exception) {
            Flux::toast(variant: 'danger', text: $exception->getMessage());

            return;
        }

        Flux::toast(variant: 'success', text: __('Work order updated.'));
        unset($this->completionNotes[$workOrderId]);
        unset($this->workOrders);
    }

    /**
     * @return list<WorkOrderStatus>
     */
    public function nextStatuses(WorkOrder $workOrder): array
    {
        return $workOrder->status->allowedNextStatuses();
    }

    public function render(): View
    {
        return view('livewire.work-orders.my-work-orders');
    }

    private function vendor(): ?Vendor
    {
        return $this->currentUser()->vendor;
    }

    private function findWorkOrder(int $workOrderId): WorkOrder
    {
        return WorkOrder::query()->where('assigned_vendor_id', $this->vendor()?->id)->findOrFail($workOrderId);
    }
}
